title: Mean, Median, Mode
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://meanmedianmode.netlify.com
# url: https://meanmedianmode.com
# tagManagerCode: GTM-W53GM9S
# googleAdClient: ca-pub-5576042369154755
themeColor: "#40dae0"

googleFonts:
  - Raleway
  - Lato
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:path

sass:
  style: compressed

plugins:
  - jekyll-sitemap