title: Mean, Median, Mode
url: https://meanmedianmode.netlify.com
# url: https://meanmedianmode.xyz
# tagManagerCode: GTM-W53GM9S
# googleAdClient: ca-pub-5576042369154755
themeColor: "#40dae0"

googleFonts:
  - Raleway
  - Lato
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed

plugins:
  - jekyll-sitemap